[package]
name = "npblog"
version = "0.1.0"
authors = ["Aqrun <aqrun@oicnp.com>"]

[dependencies]
sapper = "^0.1"
sapper_std = "^0.1"
serde="*"
serde_json="*"
serde_derive="*"
diesel = { version = "1.1.1", features = ["mysql"] }
dotenv = "0.10"

